export const SET_TYPES = 'SET_TYPES';
export const SET_MATCHUPS = 'SET_MATCHUPS';
export const GET_POKEMON_REQUEST = 'GET_POKEMON_REQUEST';
export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS';
export const GET_POKEMON_FAILURE = 'GET_POKEMON_FAILURE';
